name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install Pytest
      run: pip install pytest

    - name: Run Tests
      run: pytest test.py
